sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t vasudevmehra17/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vasudevmehra17/docker-react npm run test -- --coverage
