sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t vasudevmehra17/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vasudevmehra17/docker-react npm run test -- --coverage

    deploy: 
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-us-east-2-462763583260"
        bucket_path: "docker-react"
        on:
            branch: master
            access_key_id: $AWS_ACCESS_KEY
            secret_acess_key: "$AWS_SECRET_KEY"

